// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:af74c614-fb91-4059-953f-6d0ec14ac6c2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gYvZNZHpB",
    "aws_user_pools_web_client_id": "abdqm22annj2dk5a1gr28v93n",
    "oauth": {},
    "aws_user_files_s3_bucket": "deepwto-web-api9a69179d4be7446a8d669a50296ce2deapi-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://jpnk5vptq5djzmshkevn57a72y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ojotqixqrff5tdaarm7zpn5cfa"
};


export default awsmobile;
